// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLoop.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLoop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531234632_AddDecayAndExploration")]
    partial class AddDecayAndExploration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyLoop.Api.Entities.CellTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CellId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("FromUserId", "TransferredAt");

                    b.HasIndex("ToUserId", "TransferredAt");

                    b.ToTable("CellTransfers");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.ExploredCell", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("CellId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstVisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NeighborhoodId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "CellId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("UserId", "NeighborhoodId");

                    b.ToTable("ExploredCells");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaM2")
                        .HasColumnType("double precision");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Rank");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.TerritoryCell", b =>
                {
                    b.Property<long>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CellId"));

                    b.Property<string>("BoundaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLng")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CooldownExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ParentCellId")
                        .HasColumnType("bigint");

                    b.HasKey("CellId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentCellId");

                    b.HasIndex("CenterLat", "CenterLng");

                    b.ToTable("TerritoryCells");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HexCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStreakActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastClaimDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<int>("TopHundredFinishes")
                        .HasColumnType("integer");

                    b.Property<int>("TopTenFinishes")
                        .HasColumnType("integer");

                    b.Property<int>("TopThousandFinishes")
                        .HasColumnType("integer");

                    b.Property<int>("TopThreeFinishes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHexesCaptured")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.Claim", b =>
                {
                    b.HasOne("MyLoop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.ExploredCell", b =>
                {
                    b.HasOne("MyLoop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("MyLoop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyLoop.Api.Entities.TerritoryCell", b =>
                {
                    b.HasOne("MyLoop.Api.Entities.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyLoop.Api.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
