/// MyLoop — Application Entry Point
///
/// This file bootstraps the Flutter application by initializing platform
/// bindings, Firebase services, and the Riverpod dependency injection
/// container before launching the root widget tree.
///
/// Execution order:
///   1. Ensure Flutter engine bindings are ready (required before async work).
///   2. Initialize Firebase (auth, analytics, crashlytics, etc.).
///   3. Prefetch Google Fonts to avoid first-frame jank.
///   4. Wrap the app in [ProviderScope] so all Riverpod providers are available.
///   5. Run [MyLoopApp] as the root widget.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:myloop/app/app.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Application Bootstrap
// ─────────────────────────────────────────────────────────────────────────────

/// Application entry point.
///
/// Marked `async` because Firebase initialization is asynchronous and must
/// complete before any Firebase-dependent provider or widget is constructed.
void main() async {
  // Required before calling any plugin or async code in main().
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize the default Firebase app using platform-specific options
  // generated by FlutterFire CLI (google-services.json / GoogleService-Info.plist).
  await Firebase.initializeApp();

  // Prefetch the Nunito font to prevent layout jank on first frame.
  // This downloads and caches the font before any widget renders.
  GoogleFonts.config.allowRuntimeFetching = true;
  await GoogleFonts.pendingFonts([
    GoogleFonts.nunito(),
    GoogleFonts.nunito(fontWeight: FontWeight.w600),
    GoogleFonts.nunito(fontWeight: FontWeight.w700),
    GoogleFonts.nunito(fontWeight: FontWeight.w800),
  ]);

  // ProviderScope is the root of all Riverpod state — it must wrap the
  // entire widget tree so that providers can be read/watched anywhere.
  runApp(const ProviderScope(child: MyLoopApp()));
}
